### ISSUE TITLE
Bug with SparseMatrixCSC nzvals field when matrix generated with Not

### ISSUE THREAD

**Issue by magerton** [JuliaData/InvertedIndices.jl#23] opened 2021-04-06 22:59 UTC
This is a super helpful package -- thanks for making it!

I noticed that when working with sparse matrices, the package seems to be doing something funny with the nzval vector of structural nonzeros -- it looks like perhaps a view is created when it should be a copy maybe?

```julia
using InvertedIndices
using SparseArrays

x = [1 2 4; 0 3 0]
sp_x = sparse(x)

x[:,Not(1)] == x[:,2:end]  # true
sp_x[:,2:end].nzval == sp_x[:,Not(1)].nzval # false but should be true -- note NaN

# julia> sp_x[:,2:end].nzval
# 3-element Vector{Int64}:
#  2
#  3
#  4

# julia> sp_x[:,Not(1)].nzval
# 4-element Vector{Int64}:
#          2
#          3
#          4
#  247227520
```

**Comment by ararslan** [comment] 2024-12-03 01:57
This issue is a few years old and I can't reproduce with Julia 1.10 (current LTS) or later so I'll assume the issue was fixed at some point. I'm going to close this but feel free to reopen if you run into this again. Thanks for reporting!

**Closed as completed by ararslan** 2024-12-03 01:57 UTC
